### PR TITLE
Drop npm & typescript

### PR DESCRIPTION
**Pull request by zenhack**
IMO there's not really enough javascript here to justify pulling in NPM just for typescript; I am willing to do without a typechecker if we can simplify the build.

This patch converts the typescript javascript, and gets rid of the NPM build step.

---

I'm going to sanity check this works with ttrss before merging.

Note that users will have to update the path from build/index.js to powerbox-http-proxy.js (cc @ocdtrekkie, @orblivion)

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
Hmmm... would it be smart or reasonable to do something like typechecking when developing this thing, but publishing the JS so people don't need to build it to deploy it?

Perhaps right now it's simple enough it shouldn't matter.

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2023-01-27 19:29:36)

>    Perhaps right now it's simple enough it shouldn't matter.

This was my thinking; it also doesn't seem likely to grow dramatically.

I don't think doing an npm build is a horrible thing, but it seemed
excessive given the size of this.

**Comment by zenhack** [comment]
Confirmed working; merging.

**Comment by orblivion** [comment]
I was kind of thinking the same thing, thanks for simplifying it.

**Pull request merged**
